### ISSUE TITLE
Basic sample does not stop gracefully. How can one stop the tracking and start it again without restarting the app?

### ISSUE THREAD

**Issue by horatiu665** [Azure/azure-object-anchors#11]
**Description**

I am running the basic sample, and only added a couple of MRTK samples to have a button to toggle stuff inside the hololens, as I can't seem to connect the unity editor to do that type of thing.

I extracted the code from the Start() function inside ObjectSearch.cs in a function StartTracking() which I call upon clicking a button. So far so good, tracking starts on demand.

However, I also extracted the OnDestroy() in its own function, so I can stop the tracking on demand. When I do this, the tracking seems to pause, but a moment later I get a crash and I can't figure out where it comes from. If I debug the build, I get an exception in this function on line 10354 from the generated il2cpp file Microsoft.ObjectAnchors.Runtime.Api.WSA.cpp: 

```
// Microsoft.Azure.ObjectAnchors.status Microsoft.Azure.ObjectAnchors.NativeLibrary::aoa_object_query_compute_latest_environment_observation_async_environment_observation_topology_topology(System.IntPtr,Microsoft.Azure.ObjectAnchors.EnvironmentObservationTopology,System.IntPtr&)
IL2CPP_EXTERN_C IL2CPP_METHOD_ATTR int32_t NativeLibrary_aoa_object_query_compute_latest_environment_observation_async_environment_observation_topology_topology_m4D20EB6D1652D2593CFD6DCAF551184830C572C7 (intptr_t ___handle0, int32_t ___topology1, intptr_t* ___result2, const RuntimeMethod* method)
{
	typedef int32_t (CDECL *PInvokeFunc) (intptr_t, int32_t, intptr_t*);
	#if !FORCE_PINVOKE_INTERNAL && !FORCE_PINVOKE_Microsoft_Azure_ObjectAnchors_INTERNAL
	static PInvokeFunc il2cppPInvokeFunc;
	if (il2cppPInvokeFunc == NULL)
	{
		int parameterSize = sizeof(intptr_t) + sizeof(int32_t) + sizeof(intptr_t*);
		il2cppPInvokeFunc = il2cpp_codegen_resolve_pinvoke<PInvokeFunc>(IL2CPP_NATIVE_STRING("Microsoft.Azure.ObjectAnchors.dll"), "aoa_object_query_compute_latest_environment_observation_async_environment_observation_topology_topology", IL2CPP_CALL_C, CHARSET_NOT_SPECIFIED, parameterSize, false);
		IL2CPP_ASSERT(il2cppPInvokeFunc != NULL);
	}
	#endif

	// Native function invocation
	#if FORCE_PINVOKE_INTERNAL || FORCE_PINVOKE_Microsoft_Azure_ObjectAnchors_INTERNAL
	int32_t returnValue = reinterpret_cast<PInvokeFunc>(aoa_object_query_compute_latest_environment_observation_async_environment_observation_topology_topology)(___handle0, ___topology1, ___result2);
	#else
	int32_t returnValue = il2cppPInvokeFunc(___handle0, ___topology1, ___result2);
	#endif

	return returnValue;
}
```

So I'm guessing there is some internal thing that is not disabled properly by the code in the OnDestroy() and it still searches for the tracking system which is half-turned off. 

Here is the content of the OnDestroy() method that I think is probably not stopping enough things. 

```

            _objectAnchorsService.Pause();

            await _objectAnchorsService.StopDiagnosticsSessionAsync();

            RemoveObjectAnchorsListeners();

            _objectQueries.Clear();

            _objectAnchorsService.Dispose();

```

How do I correctly start/stop object tracking? 

**Steps to reproduce the issue**

Rename the Start() method from ObjectSearch.cs in the basic sample to something else, so unity doesn't call it automatically, then call it on demand. Then rename the OnDestroy() and call it on demand also. The tracking should stop and the app shouldn't crash, and upon starting again, it should start again just like from a cold boot.

**Expected behavior**

The tracking should stop and the app shouldn't crash, and upon starting again, it should start again just like from a cold boot.

**Screenshots**

**Development information (please complete the following information)**

 - OS: Win10
 - Development Platform\Version: Unity 2020.3.18f1
 - Azure Spatial Anchors SDK version: MRTK 2.7.2, AOA 0.15.0

**AR Device information (please complete the following information):**

 - Device:  HoloLens 2 
 - OS: latest update as of 6/oct/2021

**Additional context**

**Comment by dfields-msft** [comment]
Thanks for reporting this @horatiu665 - this may be a bug in our sample code, I'll take a look.

**Comment by craigktreasure** [comment]
This should be fixed in recent releases.
