### ISSUE TITLE
question regarding the dimensions of the 3D model and the detected objects

### ISSUE THREAD

**Issue by gft-ai** [Azure/azure-object-anchors#14]
Hi,

I wasn't quite sure where to post a question so apologies for posting it here. If there is a dedicated forum/site where I can ask a question please to let me know and I will ask there in the future.

I was wondering if the 3D model and the detected object(s) must have exactly the same dimensions or if the 3D model would be "deformed" to fit the detected object(s)?

Thank you very much!

**Comment by craigktreasure** [comment]
If I understand you correctly, you're wondering if the scale of the model needs to match that of the physical object. If that is the case then the answer is yes, . See our documentation [here](https://docs.microsoft.com/azure/object-anchors/troubleshoot/object-detection#adjust-object-query-values) on that very subject, which says:
> An app should always use a 1:1 object model for detection. The estimated scale should be close to 1 ideally within 1% error. An app could set ObjectQuery.MaxScaleChange to 0 or 0.1 to disable or enable scale estimation, and qualitatively evaluate the instance pose.

**Comment by gft-ai** [comment]
> If I understand you correctly, you're wondering if the scale of the model needs to match that of the physical object. If that is the case then the answer is yes, . See our documentation [here](https://docs.microsoft.com/azure/object-anchors/troubleshoot/object-detection#adjust-object-query-values) on that very subject, which says:
> 
> > An app should always use a 1:1 object model for detection. The estimated scale should be close to 1 ideally within 1% error. An app could set ObjectQuery.MaxScaleChange to 0 or 0.1 to disable or enable scale estimation, and qualitatively evaluate the instance pose.
> 
> 

Amazing, this was exactly what I was asking. Thank you very much!
