### ISSUE TITLE
Facing many errors before building the project

### ISSUE THREAD

**Issue by ananyanandi31** [Azure/azure-object-anchors#19]
**Description**

Hi, I am trying to run the sample MRTK project on Hololens2. I opened the project in Unity 2019.4.36f1 version. Then, I added Azure Object Anchors feature using the MixedRealityFeatureTool and modified my Build settings to Universal Windows Platform. But I am facing some errors - 

1. "error CS0246: The type or namespace name 'EnvironmentObservationTopology' could not be found (are you missing a using directive or an assembly reference?)"
2. "error CS0246: The type or namespace name 'EnvironmentObservation' could not be found (are you missing a using directive or an assembly reference?)"
3. "error CS0246: The type or namespace name 'MultiAnchorObjectPlacement' could not be found (are you missing a using directive or an assembly reference?)"

I am also facing some recurring errors when I hit play -

1. "Asset Packages/com.unity.collab-proxy/obj/Release has no meta file, but it's in an immutable folder. The asset will be ignored." 
2. "Asset Packages/com.unity.collab-proxy/obj/Release/CollabProxy.csproj.FileListAbsolute.txt has no meta file, but it's in an immutable folder. The asset will be ignored."

**Expected behavior**

No errors, so that the project can be built and run on a HoloLens 2 device.

**Development information**

 - OS: Windows
 - Development Platform\Version: Visual Studio 2019, Unity 2019.4.36f1
 - Azure Object Anchors 0.13.0

**AR Device information (please complete the following information):**

 - HoloLens 2
 - OS: Windows

**Comment by craigktreasure** [comment]
The latest version of the samples requires newer versions of the SDK. You appear to be using 0.13.0. Please use 0.18.0, which should contain all the expected types.

**Comment by craigktreasure** [comment]
Today we released version [0.19.0](https://github.com/Azure/azure-object-anchors/releases/tag/2022.3.1). I'd recommend using that with the updated samples.
