### ISSUE TITLE
Can not run sample project with holographic remoting

### ISSUE THREAD

**Issue by Jversen** [Azure/azure-object-anchors#22]
**Description**

When trying to run the sample project with holographic remoting enabled, Unity crashes. 

**Steps to reproduce the issue**

1. Set up the sample project.
1. Enable holographic remoting for play mode with the IP of the HoloLens 2.
2. Click on play with the AOASampleScene open.
3. Unity crashes. The crash log mentions 

> Got a SIGSEGV while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 
> used by your application.

**Expected behavior**

The scene should be able to be played using holographic remoting (?)

**Development information (please complete the following information)**

 - OS: Windows 10
 - Development Platform\Version: Unity 2020.3.27f1
 - Azure Object Anchors SDK version: 0.19

**AR Device information (please complete the following information):**

 - Device: HoloLens 2

**Update**

While trying to create my own app from scratch, I think I managed to pinpoint the issue. The code
```
ObjectAnchorsSession session = new ObjectAnchorsSession(accountInformation);
ObjectObserver observer = session.CreateObjectObserver();
```
causes the crash when calling CreateObjectObserver().

**Comment by charliensane** [comment]
Just wanted to concur on this.  I'm getting a crash on the same exact method when trying to remote to the hololens 2.  CreateObjectObserver()  Not sure if it is the same exact error that [Jversen](https://github.com/Jversen) reported, but it seems that it may likely be related because I've tracked it down to the same line in my code.

Unity editor crashes with...

"Unity has stopped working"
"We will now try to find a fix for the crash.  Please wait..."
"Status: There is no fix available.  Please report a bug."

```
Obtained 46 stack frames
0x00007ff8bdfa50c7 (Microsoft.Azure.ObjectAnchors) aoa_account_information_get_account_domain_wide
0x00007ff8bdf98390 (Microsoft.Azure.ObjectAnchors) aoa_object_anchors_session_create_object_observer
0x000001d6c130b135 (Mono JIT Code) (wrapper managed-to-native) Microsoft.Azure.ObjectAnchors.NativeLibrary:aoa_object_anchors_session_create_object_observer (intptr,intptr&)
0x000001d6c130afdb (Mono JIT Code) [Microsoft.Azure.ObjectAnchorsBridge_Editor.cs:1449] Microsoft.Azure.ObjectAnchors.ObjectAnchorsSession:CreateObjectObserver () 
0x000001d6c1264fe3 (Mono JIT Code) [ObjectLookup.cs:38] ObjectLookup/<Start>d__3:MoveNext () 
0x000001d6c1308612 (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
0x000001d5e6d2fcee (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000001d5e6d2f39b (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000001d6c13084cb (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
0x000001d6c13089da (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:InvokeAction (object)
0x000001d6c126eae5 (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:RunCallback (System.Threading.ContextCallback,object,System.Threading.Tasks.Task&)
0x000001d6c126e943 (Mono JIT Code) System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run (System.Threading.Tasks.Task,bool)
0x000001d5e717be03 (Mono JIT Code) System.Threading.Tasks.Task:FinishContinuations ()
0x000001d5e717b4c3 (Mono JIT Code) System.Threading.Tasks.Task:FinishStageThree ()
0x000001d6c1308953 (Mono JIT Code) System.Threading.Tasks.Task`1<Microsoft.Azure.ObjectAnchors.ObjectObserverAccessStatus>:TrySetResult (Microsoft.Azure.ObjectAnchors.ObjectObserverAccessStatus)
0x000001d6c13087b3 (Mono JIT Code) System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.Azure.ObjectAnchors.ObjectObserverAccessStatus>:SetResult (Microsoft.Azure.ObjectAnchors.ObjectObserverAccessStatus)
0x000001d6c12666b3 (Mono JIT Code) [Microsoft.Azure.ObjectAnchorsBridge_Editor.cs:1900] Microsoft.Azure.ObjectAnchors.ObjectObserver/<RequestAccessAsync>d__5:MoveNext () 
0x000001d6c1308612 (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
0x000001d5e6d2fcee (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000001d5e6d2f39b (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000001d6c13084cb (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
0x000001d6c130837a (Mono JIT Code) System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation/<>c:<.cctor>b__7_0 (object)
0x000001d6c13082b4 (Mono JIT Code) UnityEngine.UnitySynchronizationContext/WorkRequest:Invoke ()
0x000001d6c130779b (Mono JIT Code) UnityEngine.UnitySynchronizationContext:Exec ()
0x000001d6c13075bb (Mono JIT Code) UnityEngine.UnitySynchronizationContext:ExecuteTasks ()
0x000001d6b7e609b5 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007ff8a900e034 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ff8a8f4e724 (mono-2.0-bdwgc) [object.c:3064] do_runtime_invoke 
0x00007ff8a8f4e8bc (mono-2.0-bdwgc) [object.c:3111] mono_runtime_invoke 
0x00007ff717d5ab84 (Unity) scripting_method_invoke
0x00007ff717d557a4 (Unity) ScriptingInvocation::Invoke
0x00007ff717d4f0c5 (Unity) ScriptingInvocation::Invoke<void>
0x00007ff717e60c6b (Unity) Scripting::UnityEngine::UnitySynchronizationContextProxy::ExecuteTasks
0x00007ff717a378f6 (Unity) `InitPlayerLoopCallbacks'::`2'::UpdateScriptRunDelayedTasksRegistrator::Forward
0x00007ff717a1e43c (Unity) ExecutePlayerLoop
0x00007ff717a1e513 (Unity) ExecutePlayerLoop
0x00007ff717a24159 (Unity) PlayerLoop
0x00007ff718961178 (Unity) PlayerLoopController::UpdateScene
0x00007ff71894cf84 (Unity) PlayerLoopController::EnterPlayMode
0x00007ff71895c2d7 (Unity) PlayerLoopController::SetIsPlaying
0x00007ff71895e652 (Unity) Application::TickTimer
0x00007ff718da8d1a (Unity) MainMessageLoop
0x00007ff718dad5eb (Unity) WinMain
0x00007ff71a0c905e (Unity) __scrt_common_main_seh
0x00007ff9887154e0 (KERNEL32) BaseThreadInitThunk
0x00007ff9899a485b (ntdll) RtlUserThreadStart

```

The project runs if I remove the CreateObjectObserver() line.  For reference, I'm also trying to get it working in my own project following the code examples here... https://docs.microsoft.com/en-us/azure/object-anchors/concepts/sdk-overview ... because I was also unable to get the AOASampleScene project to run.

**Comment by craigktreasure** [comment]
Sorry for the delay. We're taking a look at this.

Internal reference number is 38627450.

**Comment by dfields-msft** [comment]
Thanks for reporting this issue! I did some sleuthing based on the call stack and I think I know what the problem is, but I haven't been able to reproduce it so far. Specifically, I see a codepath which could trigger an AV if Remoting was not properly connected when AOA was initialized. Can you provide the details of your XR plugin and Remoting configurations (WMR vs OpenXR, package version numbers, player app version number)?

**Comment by Jversen** [comment]
Thanks for addressing the issue!
Looks similar to @charliensane on my end. Crash log from a new barebones project (i.e. not the sample app):
```
Received signal SIGSEGV
Stack trace:
0x00007fff989950c7 (Microsoft.Azure.ObjectAnchors) aoa_account_information_get_account_domain_wide
0x00007fff98988390 (Microsoft.Azure.ObjectAnchors) aoa_object_anchors_session_create_object_observer
0x000001c7ddd8e6fd (Mono JIT Code) (wrapper managed-to-native) Microsoft.Azure.ObjectAnchors.NativeLibrary:aoa_object_anchors_session_create_object_observer (intptr,intptr&)
0x000001c7ddd8e5bb (Mono JIT Code) [Microsoft.Azure.ObjectAnchorsBridge_Editor.cs:1449] Microsoft.Azure.ObjectAnchors.ObjectAnchorsSession:CreateObjectObserver () 
0x000001c7d9ec466b (Mono JIT Code) [ObjectSearch.cs:46] ObjectSearch/<Start>d__0:MoveNext () 
0x000001c7ddd8b392 (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
0x000001c7cc759486 (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000001c7cc758f7b (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000001c7ddd8b1fb (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
0x000001c7ddd8b80a (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:InvokeAction (object)
0x000001c7d9ecf69e (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:RunCallback (System.Threading.ContextCallback,object,System.Threading.Tasks.Task&)
0x000001c7d9ecf4cb (Mono JIT Code) System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run (System.Threading.Tasks.Task,bool)
0x000001c7cdae7124 (Mono JIT Code) System.Threading.Tasks.Task:FinishContinuations ()
0x000001c7cdae6d43 (Mono JIT Code) System.Threading.Tasks.Task:FinishStageThree ()
0x000001c7ddd8b6b3 (Mono JIT Code) System.Threading.Tasks.Task`1<Microsoft.Azure.ObjectAnchors.ObjectObserverAccessStatus>:TrySetResult (Microsoft.Azure.ObjectAnchors.ObjectObserverAccessStatus)
0x000001c7ddd8b53b (Mono JIT Code) System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.Azure.ObjectAnchors.ObjectObserverAccessStatus>:SetResult (Microsoft.Azure.ObjectAnchors.ObjectObserverAccessStatus)
0x000001c7d9ec6b13 (Mono JIT Code) [Microsoft.Azure.ObjectAnchorsBridge_Editor.cs:1900] Microsoft.Azure.ObjectAnchors.ObjectObserver/<RequestAccessAsync>d__5:MoveNext () 
0x000001c7ddd8b392 (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
0x000001c7cc759486 (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000001c7cc758f7b (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000001c7ddd8b1fb (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
0x000001c7ddd8b0aa (Mono JIT Code) System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation/<>c:<.cctor>b__7_0 (object)
0x000001c7ddd8afb1 (Mono JIT Code) UnityEngine.UnitySynchronizationContext/WorkRequest:Invoke ()
0x000001c7d9eccffb (Mono JIT Code) UnityEngine.UnitySynchronizationContext:Exec ()
0x000001c7d9ecccfb (Mono JIT Code) UnityEngine.UnitySynchronizationContext:ExecuteTasks ()
0x000001c7486308ad (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007fff9b71f1e0 (mono-2.0-bdwgc) [mini-runtime.c:2849] mono_jit_runtime_invoke 
0x00007fff9b6a2ac2 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007fff9b6abb1f (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007ff71e75d7f4 (Unity) scripting_method_invoke
0x00007ff71e758ad1 (Unity) ScriptingInvocation::Invoke
0x00007ff71e7528c5 (Unity) ScriptingInvocation::Invoke<void>
0x00007ff71da2ea8b (Unity) Scripting::UnityEngine::UnitySynchronizationContextProxy::ExecuteTasks
0x00007ff71e4955f6 (Unity) `InitPlayerLoopCallbacks'::`2'::UpdateScriptRunDelayedTasksRegistrator::Forward
0x00007ff71e47cc4c (Unity) ExecutePlayerLoop
0x00007ff71e47cd23 (Unity) ExecutePlayerLoop
0x00007ff71e4837c9 (Unity) PlayerLoop
0x00007ff71f141151 (Unity) PlayerLoopController::UpdateScene
0x00007ff71f13f3d9 (Unity) Application::TickTimer
0x00007ff71f5859a1 (Unity) MainMessageLoop
0x00007ff71f5899f1 (Unity) WinMain
0x00007ff720c195ce (Unity) __scrt_common_main_seh
0x00007ff8316c7034 (KERNEL32) BaseThreadInitThunk
0x00007ff833122651 (ntdll) RtlUserThreadStart
```
As for my configuration, I am using OpenXR Plugin 1.3.1 and Mixed Reality OpenXR Plugin 1.3.1. Default settings for Holographic Remoting with the IP of the HoloLens 2 set. I am not quite sure what you mean about the player app version number?

**Comment by dfields-msft** [comment]
Thanks, with those details I was able to reproduce the crash locally and I fully understand the problem. Unfortunately, Azure Object Anchors only supports Holographic App Remoting with the Windows Mixed Reality XR plugin at this time. We will investigate adding support for the OpenXR XR plugin as well.

**Comment by dfields-msft** [comment]
I opened #25 to track adding support for OpenXR Remoting in Unity. We'll use this issue to fix the crash so instead you'll just get a clear error message in the Console stating that AOA isn't supported in the current configuration.

**Comment by Jversen** [comment]
@dfields-msft thank you!

**Comment by Jversen** [comment]
To clarify, when you say that Azure Object Anchors only supports Holographic App Remoting with the Windows Mixed Reality XR plugin, does that mean that it should work when Windows Mixed Reality is chosen instead of OpenXR in XR Plug-In Management, and that Windows XR Plugin Remoting is used instead of Holographic Remoting for Play Mode?

I don't know if some update of HoloLens 2 broke anything, but I am not able to get Windows XR Plugin Remoting working for **any** project anymore. The HL2 is stuck on showing "Receiving..." after connecting. So not an issue with AOA, but if this is indeed a problem for all HL2 users with the latest update, remoting is currently not possible regardless of configuration.

**Comment by dfields-msft** [comment]
Yes, that's correct - glad that you managed to get it working.

I have also noticed some challenges getting the connection established with recent versions of Unity. The reliable path seems to be to **manually** Connect and enter Play Mode once right after launching the editor; after that, "Connect on play" should work for the remainder of the session. This issue is not unique to using AOA and I'm following up with our Unity integration folks to try to resolve the problem.

**Comment by dfields-msft** [comment]
By the way, as far as AOA Remoting support goes, there are a couple of caveats - specifically, features which require camera access do currently not work with Remoting. This includes "Active Observation Mode" and "High Accuracy High Latency" tracking mode. However, basic object detection and tracking should work well in the Editor. We may add support for camera-dependent modes in the future; please file a feature request if this is something that would be valuable for your workflow.

**Comment by Jversen** [comment]
Thanks for the tips about getting the connection to work. Strangely enough, I am only able to get holographic remoting work once per session. It will work once when the Unity project is opened up, but to get it to work again I have to close the project and reload it.

Also, I am not able to get any object detection to work while remoting. I have placed my .ou-files such that the editor finds them and I am able to cycle through their meshes. The HL2 seems to be scanning the environment as it should, but it never detects any of the objects, even though I've decreased the coverage ratio slider down to 0.10. Could it have something to do with the input system after switching from OpenXR to Windows Mixed Reality?

**Comment by dfields-msft** [comment]
Yeah, the Remoting configuration can unfortunately be a bit finnicky... 😕 Here's a configuration which works reliably for me (with the "connect manually before entering play mode the first time" caveat):
* Unity version 2020.3.30f
* ARFoundation version 4.1.9
* WMR XR plugin version 4.6.2
* Holographic Remoting Player app version 2.7.5

**Plugin configuration:**
<img width="179" alt="image" src="https://user-images.githubusercontent.com/18537467/160167441-c200d966-7076-4a02-ad86-32c927ada4a7.png">

**Workflow:**
1. Start Unity
2. Start player app on device
3. In **Windows > XR > Windows XR Plugin Remoting**, *uncheck* "Connect on play", and click "Connect"
4. Enter and exit Play Mode one time
5. Re-enable "Connect on play" checkbox
6. Enter and exit Play Mode as needed

Our Unity integration teams are working to improve this flow and make it more reliable; please direct general feedback on Remoting in Unity here:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues
https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/issues

Meanwhile, to get AOA Remoting fully working, you will need to add the `Microsoft.Windows.MixedReality.DotNetWinRT` package to your project as detailed here:
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/tools/holographic-remoting?view=mrtkunity-2021-05#import-dotnetwinrt-into-the-project

Support for Remoting was added to the AOA SDK last fall, but depended on a few updates to the Unity XR plugin packages to work properly, which weren't publicly available at the time, so we haven't publicly documented the feature just yet. At this point, all the necessary dependencies are in place and I hope to publish updates to our samples and documentation to clarify the support for this functionality soon. Thanks for being an early adopter of this feature!

**Comment by Jversen** [comment]
@dfields-msft Thank you very much for this detailed answer. I am now able to get the object tracking working in remote. I did not have the DotNetWinRT package installed before so maybe that was the culprit? 

Only problem that remains is that the display starts flickering in the HL2 after a few seconds of remote video. This however is a more general issue. I am happy that I'll be able to continue my work :)

**Comment by Jversen** [comment]
When the Windows XR Plugin Remoting is used, there is a note in the inspector that says "The editor uses player settings from the 'Standalone' platform for play mode [...]". Since this means that the editor is not running UWP, we encounter en error in the following snippet from https://docs.microsoft.com/en-us/azure/object-anchors/concepts/sdk-overview 
```
#if WINDOWS_UWP
        SpatialCoordinateSystem worldOrigin = ObjectAnchorsWorldManager.WorldOrigin;
        if (worldOrigin != null)
        {
            coordinateSystem = await Task.Run(() => worldOrigin.TryToSpatialGraph());
        }
#endif

        if (!coordinateSystem.HasValue)
        {
            Debug.LogError("no coordinate system?");
            return;
        }
```

Is there any workaround to make use of another coordinate system while running remote?

**Comment by Jversen** [comment]
Thank you again!
I believe there is only one thing remaining to fully apply [the runtime SDK basics](https://docs.microsoft.com/en-us/azure/object-anchors/concepts/sdk-overview) with remoting. The following code
```
using Microsoft.Azure.ObjectAnchors;

var InstanceChangedHandler = new Windows.Foundation.TypedEventHandler<ObjectInstance, ObjectInstanceChangedEventArgs>((sender, args) =>
{
    // Try to query the current instance state.
    ObjectInstanceState? state = sender.TryGetCurrentState();

    if (state.HasValue)
    {
        // Process latest state via state.Value.
        // An object pose includes scale, rotation and translation, applied in
        // the same order to the object model in the centered coordinate system.
    }
    else
    {
        // This object instance is lost for tracking, and will never be recovered.
        // The caller can detach the Changed event handler from this instance
        // and dispose it.
        sender.Dispose();
    }
});
```
makes use of `Windows.Foundation.TypedEventHandler` which is part of UWP, and can't be run through the editor. Is there any way of substituting this to something else? On the other hand, in the sample project, there is no reference to an InstanceChangedHandler or any TypedEventHandler so maybe I could ignore this part in my project?

**Comment by dfields-msft** [comment]
As of the recent 0.23.0 release, all known issues* with Remoting are resolved, and documentation and samples have been updated to reflect this. See: https://docs.microsoft.com/en-us/azure/object-anchors/quickstarts/unity-remoting

Please let us know if you encounter any additional challenges using Remoting with Azure Object Anchors!

\* OpenXR support is still pending per #25.
