### ISSUE TITLE
Unity 2020: Facing many errors in the sample project

### ISSUE THREAD

**Issue by ananyanandi31** [Azure/azure-object-anchors#23]
**Description**

Hi, I am trying to run the sample MRTK project on Hololens2. I opened the project in Unity 2020.3.22f1 version. Then, I added Azure Object Anchors feature using the MixedRealityFeatureTool and modified my Build settings to Universal Windows Platform. But I am facing some errors - 

Assets\MixedReality.AzureObjectAnchors\Scripts\EnvironmentObservationRenderer.cs(19,12): error CS0246: The type or namespace name 'ObjectQuery' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\EnvironmentObservationRenderer.cs(25,12): error CS0246: The type or namespace name 'EnvironmentObservationTopology' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\MeshLoader.cs(39,64): error CS0246: The type or namespace name 'EnvironmentObservation' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(76,16): error CS0246: The type or namespace name 'ObjectObservationMode' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(198,22): error CS0246: The type or namespace name 'ObjectAnchorsBoundingBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(198,60): error CS0246: The type or namespace name 'ObjectQuery' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\OverlayDebugText.cs(16,17): error CS0246: The type or namespace name 'IObjectAnchorsService' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(458,74): error CS0246: The type or namespace name 'ObjectAnchorsServiceStatus' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(463,37): error CS0246: The type or namespace name 'ObjectAnchorsServiceStatus' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(480,73): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(485,36): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTrackerDiagnostics.cs(31,17): error CS0246: The type or namespace name 'IObjectAnchorsService' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(496,73): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(501,36): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(506,71): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTrackerDiagnostics.cs(34,41): error CS0246: The type or namespace name 'IObjectAnchorsService' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(511,34): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(516,34): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\SpatialMappingController.cs(32,17): error CS0246: The type or namespace name 'IObjectAnchorsService' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(617,48): error CS0246: The type or namespace name 'ObjectAnchorsBoundingBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(59,17): error CS0246: The type or namespace name 'ObjectObservationMode' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\SearchAreaController.cs(45,16): error CS0246: The type or namespace name 'ObjectAnchorsBoundingBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(122,66): error CS0246: The type or namespace name 'ObjectInstanceTrackingMode' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(260,17): error CS0246: The type or namespace name 'IObjectAnchorsService' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\SearchAreaController.cs(58,17): error CS0246: The type or namespace name 'IObjectAnchorsService' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(335,39): error CS0246: The type or namespace name 'ObjectAnchorsBoundingBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(335,77): error CS0246: The type or namespace name 'ObjectQuery' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\ObjectTracker.cs(273,20): error CS0246: The type or namespace name 'ObjectQuery' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackableObjectData.cs(98,39): error CS0246: The type or namespace name 'ObjectAnchorsBoundingBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackableObjectData.cs(80,16): error CS0246: The type or namespace name 'ObjectAnchorsBoundingBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackableObjectSearch.cs(19,17): error CS0246: The type or namespace name 'IObjectAnchorsService' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObjectData.cs(12,40): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObjectData.cs(24,16): error CS0246: The type or namespace name 'ObjectAnchorsLocation' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObjectData.cs(41,16): error CS0246: The type or namespace name 'ObjectInstanceTrackingMode' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObject.cs(85,38): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObjectData.cs(59,16): error CS0246: The type or namespace name 'ObjectAnchorsBoundingBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObject.cs(138,45): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObject.cs(40,17): error CS0246: The type or namespace name 'IObjectAnchorsServiceEventArgs' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObject.cs(42,17): error CS0246: The type or namespace name 'MultiAnchorObjectPlacement' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObject.cs(46,44): error CS0246: The type or namespace name 'ObjectInstanceTrackingMode' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\TrackedObject.cs(53,44): error CS0246: The type or namespace name 'ObjectInstanceTrackingMode' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedReality.AzureObjectAnchors\Scripts\AutonomousSearchArea.cs(23,17): error CS0246: The type or namespace name 'IObjectAnchorsService' could not be found (are you missing a using directive or an assembly reference?)

**Screenshots**

I've attached the Screenshots of these errors.

**Development information (please complete the following information)**

 - OS: Windows 10
 - Development Platform\Version:  Visual Studio 2019, Unity 2020.3.22f1

**Additional context**

Error 1 & Error 2 pictures are the errors faced by me in the sample project.
Error 3 pictures consist of the errors that occurred when I imported the Object Anchors Folder to a new Empty project.

![Error3](https://user-images.githubusercontent.com/46529737/157816474-2c39386c-ce42-4e4e-ba28-01dd71e1a3ec.png)
![Error2](https://user-images.githubusercontent.com/46529737/157816475-a7203f9c-befb-4399-8935-8b46b6cda987.png)
![Error1](https://user-images.githubusercontent.com/46529737/157816478-0ce9b631-5aff-4282-8b4a-2bbacd2c8003.png)

**Comment by craigktreasure** [comment]
Sorry to hear you're facing issues. Did you follow the instructions [here](https://docs.microsoft.com/azure/object-anchors/quickstarts/upgrade-unity-quickstart-to-2020) to update the code for Unity 2020? There are breaking changes between Unity 2019 and 2020, so it's hard to make a sample that seamlessly works with both without overcomplicating it.
