### ISSUE TITLE
NuGet Package should include PerceptionDevice.dll

### ISSUE THREAD

**Issue by fieldsJacksonG** [Azure/azure-object-anchors#29]
The NuGet package here should include PerceptionDevice.dll:
https://www.nuget.org/packages/Microsoft.Azure.ObjectAnchors.Runtime.WinRT/

Microsoft.Azure.ObjectAnchors.dll depends on PerceptionDevice.dll:
>dumpbin /dependents Microsoft.Azure.ObjectAnchors.dll
PerceptionDevice.dll
(among other dependencies)

When building an Azure Object Anchor project on a build server, the remote machine does not have PerceptionDevice in any binary search path, so Microsoft.Azure.ObjectAnchors.dll will fail to load and the build fails.

I can workaround this by manually copying PerceptionDevice.dll from the Holographic Remoting NuGet package:
https://www.nuget.org/packages/Microsoft.Holographic.Remoting.OpenXr/

**Comment by craigktreasure** [comment]
@dfields-msft

**Comment by dfields-msft** [comment]
PerceptionDevice.dll is part of the Windows OS. Can you elaborate on the failures you're encountering? Redistributing the Remoting version is not an appropriate solution since that version is specifically tailored for Remoting purposes.

**Comment by dfields-msft** [comment]
@fieldsJacksonG what specific Windows OS is the "build server" running? Why does the build process involve loading Microsoft.Azure.ObjectAnchors.dll and its dependencies?

**Comment by fieldsJacksonG** [comment]
Closing - this is more of a quirk in the build process for the engine building the project.
