### ISSUE TITLE
Convert a 3D model

### ISSUE THREAD

**Issue by qazqaz12378** [Azure/azure-object-anchors#3]
Excuse me, do you need any more requirements for the model? The Cola I created with 3DMAX is not recognized. Can I display the recognition level of the model. Or can we provide the available FBX format model?

**Comment by craigktreasure** [comment]
Hey @qazqaz12378. Thanks for reaching out. I'm a bit confused, but I'll restate what I think you're asking and we can go from there.

It sounds like you created a model of a real world object using some 3D software. Then, I'm assuming you converted that 3D model into an Object Anchors model ([docs](https://docs.microsoft.com/azure/object-anchors/quickstarts/get-started-model-conversion)). You're now trying to detect your physical object using a HoloLens 2. Is this correct?

Are you using one of our sample applications to detect your object?

Have you reviewed the [FAQ](https://docs.microsoft.com/azure/object-anchors/faq) in our docs? The "What should I do if the Object Anchors runtime cannot detect my object?" question may be helpful. Also, if you're creating a virtual representation of a physical object from scratch, you'll want to make sure the scale is correct.

**Comment by qazqaz12378** [comment]
Sorry, I can't speak English. I use Google translation

（It sounds like you created a model of a real world object using some 3D software. Then, I'm assuming you converted that 3D model into an Object Anchors model (docs). You're now trying to detect your physical object using a HoloLens 2. Is this correct?） YES
（Are you using one of our sample applications to detect your object?） yes
I use Rubik's cube and coke model, scale is correct

**Comment by craigktreasure** [comment]
I see. I'm concerned that those objects may be a bit too small. Our recommendation in our [best practices](https://docs.microsoft.com/azure/object-anchors/best-practices#ingestion) indicates to use objects between 1 and 10 meters. Could you try a larger object?

**Comment by qazqaz12378** [comment]
OK, I'm looking for some big objects。
thank you

**Comment by craigktreasure** [comment]
Closing this for now. Feel free to reach out if you have further questions.
