### ISSUE TITLE
Unity may hang when restarting Play Mode when AOA SDK is used

### ISSUE THREAD

**Issue by dfields-msft** [Azure/azure-object-anchors#33]
**Description**

The Unity Editor may hang and need to be forcefully restarted when the AOA SDK is used in the scene, upon exiting and re-entering Play Mode (or otherwise causing the AppDomain to be reset, e.g. recompiling scripts).

**Steps to reproduce the issue**

1. Open the "Visualization" scene in the "basic" sample, and fill in a path to a .ou file in the "Visualizer" game object
2. Enter Play Mode, exit, and re-enter

**Expected behavior**

Unity Editor continues to function, and enters Play Mode a second time.
Instead, the Editor hangs permanently and must be forcibly terminated and restarted.

**Development information (please complete the following information)**

 - OS: Windows
 - Azure Spatial Anchors SDK version: 0.21.0

**Comment by craigktreasure** [comment]
Fixed in [0.23.0](https://github.com/Azure/azure-object-anchors/releases/tag/2022.7.1-preview).
