### ISSUE TITLE
Conversion quickstart waits for job completion without success

### ISSUE THREAD

**Issue by powellsky** [Azure/azure-object-anchors#4]
Hello. I am trying to use conversion quick start solution to retrieve object anchor for my *obj 3D model. I am following steps from [this](https://docs.microsoft.com/en-us/azure/object-anchors/quickstarts/get-started-model-conversion) tutorial. 

![issue](https://user-images.githubusercontent.com/33156959/115962670-6b1e2a00-a514-11eb-992b-fdefab1f2c76.png)

The process seems to be stuck while waiting for job completion. I even exceeded timeout to 2 hours, but still without any success. The file has roughly 6 MB and around 60k vertices. I thought that maybe it is too big so I decreased it to 1MB and 15k vertices, but same issue occurs. 

I understand that from best practices model should be between 1-10 meters, in my case model is smaller than that, but still, shouldn't the process at least finish?  

Thank you in advance.

**Comment by craigktreasure** [comment]
I'm sorry to hear you're having issues with model conversion. Thanks for reporting the issue. We're investigating.

**Comment by craigktreasure** [comment]
Internal reference number is 32893849.

**Comment by craigktreasure** [comment]
Hey @powellsky, I think it's likely that if you were to check the status of that job today, it would report a failure. We appear to be failing to convert your 3D model for some reason. There's likely some attribute about that particular model that is causing issues. Would it be possible for you to share that particular `obj` file with us? It would help us investigate further. In this particular case, it's difficult to investigate the issue without it.

**Comment by craigktreasure** [comment]
@powellsky Feel free to also reach out to aoafeedback@microsoft.com so that we can help resolve this.

**Comment by powellsky** [comment]
@craigktreasure Sorry for late respond, and thank you for the answer. Here is the *obj fille I am trying to convert: [Mediafire-link](https://www.mediafire.com/file/j412v3ijxyap6it/low3.obj/file)

**Comment by craigktreasure** [comment]
Thanks for sharing that. We'll take a look and get back to you.

**Comment by craigktreasure** [comment]
Hey @powellsky. I'm having a hard time reproducing the issue with the file you sent. The service successfully created a model for me. I used the following default settings from the sample:
```csharp
        // Gravity direction of 3D model
        public Vector3 Gravity = new Vector3(0.0f, -1.0f, 0.0f);

        // The unit of measurement of the 3D model
        [JsonConverter(typeof(StringEnumConverter))]
        public AssetLengthUnit AssetDimensionUnit = AssetLengthUnit.Meters;
```

Can you tell me what values you used for `Gravity` and `AssetDimensionUnit`?
