### ISSUE TITLE
Azure Object anchors for HoloLens 1 & photogrammetry 3D scanned object

### ISSUE THREAD

**Issue by ZaidZaim** [Azure/azure-object-anchors#5]
Dear @craigktreasure & team,

I have four questions: 
1. Is it possible to use your Azure Object Anchors for HoloLens 1? As Hololens 1 has spatial mapping and could also map or recognize objects. 

2. For training the Azure object service: Is it a must that the uploaded 3D model have a a real scale of the object to detect? I have some experience with photogrametry, I am not always able to create the real scale.

3. Does the HoloLens recognize an object from far, or is there a specific minimal size and distance? Can you provide what measures and scale of an object you recommend.
I intend to detect object similar to the ones in the picture attached.
![20210427_233225](https://user-images.githubusercontent.com/43517319/116315534-f6b3e700-a7b0-11eb-83cd-a9337d1a0f4e.jpg)

4. Could you provide a guidance on how to integrate the service in premade unity project and what Unity and MRTK versions are recommended?

I am very looking forward to hearing from you and thanks in advance.

**Comment by craigktreasure** [comment]
Hey @ZaidZaim. Great questions. Let me see if I can answer some of these for you.

1. Can I use HoloLens 1?
    Today, we only support HoloLens 2 and our SDK will not work on HoloLens 1. Per our [FAQ](https://docs.microsoft.com/azure/object-anchors/faq): "Q: What devices does Object Anchors support? A: HoloLens 2." The advancements in the HoloLens 2 made it possible for us to hit accuracy and performance requirements. 
2. Do we need an accurate scale for the model?
    Yes. The scale plays an important role in training and detection. It should be somewhat accurate. Probably within 10% ideally.
3. Object detection recommendations
    You'll find lots of information about those very questions in our [best practices](https://docs.microsoft.com/azure/object-anchors/best-practices) and [FAQ](https://docs.microsoft.com/azure/object-anchors/faq).
4. Unity and MRTK guidance
    We don't currently have a guide for existing applications, but we are planning to create one. For now, I'd recommend getting familiar with our [sample](https://docs.microsoft.com/azure/object-anchors/quickstarts/get-started-unity-hololens-mrtk) and recreating in your own app.
    We currently support Unity 2019 LTS, but Unity 2020 LTS should work as well. We're planning to have official support for Unity 2020 LTS soon.

I don't know what scenarios you're after or the requirements you may have, but I believe the last picture you showed would be a good fit for Azure Object Anchors today. The others are objects we're looking into for the future.

Have you also considered [Azure Spatial Anchors](https://docs.microsoft.com/azure/object-anchors/overview)? That service supports HoloLens 1. The technology is a bit different. Your scenarios and accuracy requirements would determine which one is the best fit. I've seen people do really cool things by combining the two together as well.
