### ISSUE TITLE
Sample Apps not working

### ISSUE THREAD

**Issue by veeruby-developer** [Azure/azure-object-anchors#8]
**Description**:
I have followed the tutorial of quick start of both [HoloLens](https://docs.microsoft.com/en-us/azure/object-anchors/quickstarts/get-started-unity-hololens) and [HoloLens2 with MRTK](https://docs.microsoft.com/en-us/azure/object-anchors/quickstarts/get-started-unity-hololens-mrtk), but HoloLens was unable to detect the model.
on screen status message is as follow.

For HoloLen2 with MRTK:
AOA status :paused(after start searching, it will change to running)
Tracked:0;
Models:1;
querying:false

For Basic HoloLens App:
[Time] Loading Model(model name)
[Time] detection attempted
[Time] detection attempted
[Time] detection attempted
.
.

3D Model Size:
length:91cm
width:79cm
height:152cm

unity:2019.4.18
AOA:0.13.0

am I missing out on something....

**Comment by Xudarker** [comment]
dude, I'm with you the same problem,how did you come out with the message status models:1?

**Comment by craigktreasure** [comment]
@veeruby-developer Sorry to hear you're having issues. It sounds like the sample app is picking up your model file, but it's not detecting it for some reason. Here are a few thoughts:

* My first guess is that there was something wrong with the values you provided during model conversion. Perhaps the gravity direction or scale unit? It's important that those are specified correctly during model conversion or else your object won't be detected in the apps correctly. See the "What is the gravity direction and unit required by the model conversion service? How can we figure them out?" question and answer [here](https://docs.microsoft.com/azure/object-anchors/faq). Double check the values you used there and let me know how it goes.
* You can also follow the instructions [here](https://docs.microsoft.com/azure/object-anchors/visualize-converted-model) to visualize the converted model to see if there's anything obvious that appears wrong.
* Assuming the gravity direction and scale unit are correct, you might take a look at the document [here](https://docs.microsoft.com/azure/object-anchors/detect-difficult-object) to tweak the detection settings for objects that are a bit tougher to detect.

**Comment by veeruby-developer** [comment]
@Xudarker I have added the converted 3d model in HoloLens2 folder "Internal Storage > 3D Objects" may be that is why it is showing  no of models as 1.

**Comment by Xudarker** [comment]
> @Xudarker I have added the converted 3d model in HoloLens2 folder "Internal Storage > 3D Objects" may be that is why it is showing no of models as 1.

thanks,my problem has solved.

**Comment by veeruby-developer** [comment]
@craigktreasure thank you for the quick response, I will try your suggestions and let you know.

**Comment by craigktreasure** [comment]
@veeruby-developer Following our discussion, i've also added a new page to our documentation to [troubleshoot object detection](https://docs.microsoft.com/azure/object-anchors/troubleshoot/object-detection) that has what I mentioned above as well as a few other suggestions.
